<a href="https://colab.research.google.com/github/Ashi743/deep-learning-/blob/main/Backpropagation__regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
df= pd.DataFrame([ [8,8,4], [7,9,5], [6,10,6], [5,12,7] ], columns=['X1','X2','Y'])
df

X1  X2  Y
0   8   8  4
1   7   9  5
2   6  10  6
3   5  12  7

In [66]:
#keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten

In [67]:
model= Sequential()
model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))
model.summary()
model.get_weights()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

[array([[-0.43974322,  0.50359595],
        [ 0.44523406, -1.2117636 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.1718229 ],
        [-0.53591675]], dtype=float32),
 array([0.], dtype=float32)]

In [70]:
new_weights= [np.array([[ 0.1, 0.1],
                        [ 0.1, 0.1]], dtype=np.float32),
              np.array( [0., 0.], dtype=np.float32),
              np.array([[ 0.1],
                        [ 0.1]], dtype=np.float32),

              np.array([0.], dtype=np.float32)]
model.set_weights(new_weights)

In [71]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [72]:
optimizer= keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [74]:
model.fit(df[["X1","X2"]].values, df["Y"].values, epochs=75)

Epoch 1/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 27.6081
Epoch 2/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 27.5247
Epoch 3/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 27.4406
Epoch 4/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 27.3559
Epoch 5/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 27.2705
Epoch 6/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 27.1845
Epoch 7/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 27.0978
Epoch 8/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 27.0104
Epoch 9/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 26.9223
Epoch 10/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 26.8336
Epoch 11/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 26.7441
Epoch 12/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 26.6539
Epoch 13/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 26.5631
Epoch 14/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 26.4715
Epoch 15/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 26.3792
Epoch 16/75
1/1 ━━━

In [18]:
# layer_dims=  2 inp, 2 nodeshidden, 1 outputnode

In [8]:
#architecture input
#weights init
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters= {}
  L =len(layer_dims)
  for l in range(1,L):
    parameters['W' + str(l)]= np.ones ( (layer_dims[l-1] ,layer_dims[l]) )*0.1
    parameters['b' + str(l)]= np.zeros( (layer_dims[l], 1) )
  return parameters

In [31]:
layers_dims= [2,2,1]
print(np.ones ( (layers_dims[0], layers_dims[1]  )) ) #2x2
print(np.ones ( (layers_dims[1], layers_dims[2]  )))  #2x1

print(np.ones ( (1,1  )))

[[1. 1.]
 [1. 1.]]
[[1.]
 [1.]]
[[1.]]


In [12]:
len([2,2,1])

3

In [34]:
len(initialize_parameters([2,2,1]))

4

In [33]:
def linear_forward(A_prev, W, b):
  Z= np.dot(W.T, A_prev) + b
  return Z

In [49]:
#forward propogation
def L_layer_forward(X, parameters):
  A= X
  L= len(parameters) //2  #number of layers in the neural network
  for l in range(1 , L+1):
    A_prev= A
    W1= parameters['W' + str(l)]
    b1= parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", W1)
    print("b"+str(l)+": ", b1)
    print("--"*20)

    A= linear_forward(A_prev, W1, b1)
    print("A"+str(l)+": ", A)

    print("--"*20)

  return A, A_prev



In [44]:
A1[0][0]

1.6

In [62]:
def update_parameters(parameters, y ,y_hat ,A1, X):
  parameters["W2"][0][0]+= 2*(0.001 * (y - y_hat)*A1[0][0]).item()
  parameters["W2"][1][0]+= 2*(0.001 * (y - y_hat)*A1[0][0]).item()
  parameters["b2"][0][0]+= 2*(0.001 * (y - y_hat)).item()

  parameters["W1"][0][0]+= 2*(0.001 * (y - y_hat)*parameters["W2"][0][0]*X[0][0]).item()
  parameters["W1"][0][1]+= 2*(0.001 * (y - y_hat)*parameters["W2"][0][0]*X[1][0]).item()
  parameters["b1"][0][0]+= 2*(0.001 * (y - y_hat)*parameters["W2"][0][0]).item()

  parameters["W1"][1][0]+= 2*(0.001 * (y - y_hat)*parameters["W2"][1][0]*X[0][0]).item()
  parameters["W1"][1][1]+= 2*(0.001 * (y - y_hat)*parameters["W2"][1][0]*X[1][0]).item()
  parameters["b1"][1][0]+= 2*(0.001 * (y - y_hat)*parameters["W2"][1][0]).item()


In [63]:
X= df[["X1" ,"X2"]].values[0].reshape(2,1)    # no.of feat x no.of training examples
y= df[["Y"]].values[0][0]   # just the value

#init parameters
parameters= initialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X, parameters)
update_parameters(parameters, y ,y_hat ,A1, X)
parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
----------------------------------------


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [64]:
X= df[["X1" ,"X2"]].values[1].reshape(2,1)    # no.of feat x no.of training examples
y= df[["Y"]].values[1][0]   # just the value

#init parameters
parameters= initialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X, parameters)
update_parameters(parameters, y ,y_hat ,A1, X)
parameters

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
----------------------------------------


{'W1': array([[0.10753323, 0.10968558],
        [0.10753323, 0.10968558]]),
 'b1': array([[0.00107618],
        [0.00107618]]),
 'W2': array([[0.114976],
        [0.114976]]),
 'b2': array([[0.00936]])}

In [65]:
#epochs
parameters= initialize_parameters([2,2,1])
epochs= 5

for i in range(epochs):
  Loss= []
  for j in range(df.shape[0]):
    X= df[["X1" ,"X2"]].values[j].reshape(2,1)    # no.of feat x no.of training examples
    y= df[["Y"]].values[j][0]   # just the value

    y_hat,A1= L_layer_forward(X, parameters)
    update_parameters(parameters, y ,y_hat ,A1, X)
    Loss.append(np.square(y-y_hat).item())
  print("Epoch - ", i+1, "Loss - ", np.array(Loss).mean())

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
----------------------------------------
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.00736]]
----------------------------------------
A2:  [[0.38876757]]
----------------------------------------
A0:  [[ 6]
 [10]]
W1:  [[0.11481311 0.11716504]
 [0.11481311 0.11716504]]
b1:  [[0.00199863]
 [0.00199863]]
----------------------------------------
A1:  [[1.83900839]
 [1.8766392 ]]
----------------------------------------
A1:  [[1.83900839]
 [1.8766392 ]]
W2:  [[0.12751067]
 [0.12